# Generated by Django 5.2.17 on 2026-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportpackage",
            name="content_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="exportpackage",
            name="error",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="exportpackage",
            name="snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="exportpackage",
            name="storage_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
