# Generated by Django 5.1.11 on 2026-08-19 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0002_initial"),
        ("evidence", "0002_initial"),
        ("processing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_path", models.TextField(blank=True)),
                ("source_hash_reference", models.CharField(blank=True, max_length=128)),
                ("processor_name", models.CharField(max_length=100)),
                ("processor_version", models.CharField(max_length=40)),
                ("processing_timestamp", models.DateTimeField(auto_now_add=True)),
                ("processing_status", models.CharField(default="normalized", max_length=30)),
                ("artifact_type", models.CharField(default="file_metadata", max_length=60)),
                ("content", models.JSONField(default=dict)),
                ("limitations", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="cases.case",
                    ),
                ),
                (
                    "processing_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="processing.processingrun",
                    ),
                ),
                (
                    "source_evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="evidence.evidenceitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="investigations.artifact",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="cases.case",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("finding_text", models.TextField()),
                (
                    "examiner_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Examiner-approved conclusion"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("not_reviewed", "Not reviewed"),
                            ("in_review", "In review"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="not_reviewed",
                        max_length=30,
                    ),
                ),
                ("reviewer_comments", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="cases.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestigatorNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investigations.artifact",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="cases.case",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProvenanceLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("relationship", models.CharField(default="derived_from", max_length=80)),
                ("rationale", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provenance_links",
                        to="investigations.artifact",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenance_links",
                        to="cases.case",
                    ),
                ),
                (
                    "source_evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provenance_links",
                        to="evidence.evidenceitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("event_type", models.CharField(max_length=80)),
                ("summary", models.TextField()),
                (
                    "interpretation_status",
                    models.CharField(
                        choices=[
                            ("observed", "Observed evidence"),
                            ("normalized", "Normalized interpretation"),
                            ("suggestion", "Machine-generated suggestion"),
                            ("approved", "Examiner-approved conclusion"),
                        ],
                        default="observed",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timeline_events",
                        to="investigations.artifact",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "ordering": ["observed_at"],
            },
        ),
        migrations.CreateModel(
            name="FindingSupport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investigations.artifact",
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supports",
                        to="investigations.finding",
                    ),
                ),
                (
                    "timeline_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="investigations.timelineevent",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["case", "artifact_type"], name="investigati_case_id_349f17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["source_evidence", "created_at"], name="investigati_source__663ea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["case", "review_status"], name="investigati_case_id_7c740f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["case", "created_at"], name="investigati_case_id_500008_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="provenancelink",
            index=models.Index(
                fields=["case", "created_at"], name="investigati_case_id_413796_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="provenancelink",
            constraint=models.UniqueConstraint(
                fields=("source_evidence", "artifact", "relationship"),
                name="unique_provenance_link",
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["case", "observed_at"], name="investigati_case_id_0d4d3e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["case", "event_type"], name="investigati_case_id_28db8d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="findingsupport",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("artifact__isnull", False), ("timeline_event__isnull", False), _connector="OR"
                ),
                name="finding_support_has_source",
            ),
        ),
    ]
