# Generated by Django 5.1.11 on 2026-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investigations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="finding_basis",
            field=models.CharField(
                choices=[
                    ("observed", "Observed evidence"),
                    ("interpreted", "Normalized interpretation"),
                ],
                default="observed",
                max_length=30,
            ),
        ),
    ]
