# Generated by Django 5.2.17 on 2026-09-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investigations", "0002_finding_finding_basis"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="timestamp_format",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="timestamp_meaning",
            field=models.CharField(default="unknown", max_length=80),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="timestamp_original",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="timestamp_precision",
            field=models.CharField(default="unknown", max_length=80),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="timestamp_uncertainty",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="timestamp_zone",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="observed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
