from django.urls import path
from .views import (
    ArtifactDetail,
    ArtifactList,
    ArtifactProvenance,
    AuditList,
    BookmarkListCreate,
    CaseDetail,
    CaseListCreate,
    EvidenceDetail,
    EvidenceListCreate,
    EvidenceVerify,
    ExportCreate,
    FindingDetail,
    FindingListCreate,
    FindingSupportListCreate,
    GlobalAuditList,
    JobDetail,
    JobListCreate,
    NoteListCreate,
    ParticipantList,
    ProvenanceList,
    ReportDetail,
    ReportListCreate,
    TimelineList,
)

urlpatterns = [
    path("cases/", CaseListCreate.as_view()),
    path("cases/<uuid:pk>/", CaseDetail.as_view()),
    path("cases/<uuid:case_id>/participants/", ParticipantList.as_view()),
    path("cases/<uuid:case_id>/evidence/", EvidenceListCreate.as_view()),
    path("evidence/<uuid:evidence_id>/", EvidenceDetail.as_view()),
    path("evidence/<uuid:evidence_id>/verify/", EvidenceVerify.as_view()),
    path("cases/<uuid:case_id>/jobs/", JobListCreate.as_view()),
    path("jobs/<uuid:job_id>/", JobDetail.as_view()),
    path("cases/<uuid:case_id>/artifacts/", ArtifactList.as_view()),
    path("artifacts/<uuid:artifact_id>/", ArtifactDetail.as_view()),
    path("artifacts/<uuid:artifact_id>/provenance/", ArtifactProvenance.as_view()),
    path("cases/<uuid:case_id>/timeline/", TimelineList.as_view()),
    path("cases/<uuid:case_id>/provenance/", ProvenanceList.as_view()),
    path("cases/<uuid:case_id>/findings/", FindingListCreate.as_view()),
    path("findings/<uuid:finding_id>/", FindingDetail.as_view()),
    path("findings/<uuid:finding_id>/support/", FindingSupportListCreate.as_view()),
    path("cases/<uuid:case_id>/reports/", ReportListCreate.as_view()),
    path("reports/<uuid:report_id>/", ReportDetail.as_view()),
    path("cases/<uuid:case_id>/audit/", AuditList.as_view()),
    path("audit/", GlobalAuditList.as_view()),
    path("cases/<uuid:case_id>/bookmarks/", BookmarkListCreate.as_view()),
    path("cases/<uuid:case_id>/notes/", NoteListCreate.as_view()),
    path("cases/<uuid:case_id>/exports/", ExportCreate.as_view()),
]
