# Generated by Django 5.1.11 on 2026-08-19 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="caseparticipant",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="caseparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="case_participation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["status"], name="cases_case_status_5f99d2_idx"),
        ),
        migrations.AddIndex(
            model_name="case",
            index=models.Index(fields=["owner", "status"], name="cases_case_owner_i_7e79ae_idx"),
        ),
        migrations.AddIndex(
            model_name="caseparticipant",
            index=models.Index(
                fields=["case", "permission"], name="cases_casep_case_id_baf9aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseparticipant",
            index=models.Index(fields=["user", "case"], name="cases_casep_user_id_cb1146_idx"),
        ),
        migrations.AddConstraint(
            model_name="caseparticipant",
            constraint=models.UniqueConstraint(
                fields=("case", "user"), name="unique_case_participant"
            ),
        ),
    ]
