# Generated by Django 5.2.17 on 2026-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="ledger_sequence",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
