# Generated by Django 5.1.11 on 2026-08-19 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustodyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=60)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceHash",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("algorithm", models.CharField(default="SHA-256", max_length=20)),
                ("value", models.CharField(max_length=128)),
                ("source", models.CharField(default="calculated", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("evidence_type", models.CharField(default="synthetic_file", max_length=60)),
                ("display_name", models.CharField(max_length=200)),
                ("original_path", models.TextField()),
                ("acquisition_metadata", models.JSONField(blank=True, default=dict)),
                ("hash_algorithm", models.CharField(default="SHA-256", max_length=20)),
                ("expected_hash", models.CharField(blank=True, max_length=64)),
                ("calculated_hash", models.CharField(blank=True, max_length=64)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("mismatch", "Mismatch"),
                            ("unreadable", "Unreadable"),
                        ],
                        default="unverified",
                        max_length=30,
                    ),
                ),
                ("read_only", models.BooleanField(default=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
