# Generated by Django 5.1.11 on 2026-08-19 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0002_initial"),
        ("evidence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="custodyevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="custodyevent",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custody_events",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_items",
                to="cases.case",
            ),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="registered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registered_evidence",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evidencehash",
            name="evidence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hashes",
                to="evidence.evidenceitem",
            ),
        ),
        migrations.AddField(
            model_name="custodyevent",
            name="evidence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="custody_events",
                to="evidence.evidenceitem",
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceitem",
            index=models.Index(
                fields=["case", "verification_status"], name="evidence_ev_case_id_48194f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidenceitem",
            index=models.Index(
                fields=["case", "registered_at"], name="evidence_ev_case_id_bd0ce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidencehash",
            index=models.Index(
                fields=["evidence", "algorithm"], name="evidence_ev_evidenc_dec94a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="custodyevent",
            index=models.Index(
                fields=["case", "created_at"], name="evidence_cu_case_id_3f42c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="custodyevent",
            index=models.Index(
                fields=["evidence", "created_at"], name="evidence_cu_evidenc_eeec8c_idx"
            ),
        ),
    ]
