# Generated by Django 5.1.11 on 2026-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evidence", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidenceitem",
            name="is_synthetic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="limitations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="warnings",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
