# Generated by Django 5.2.17 on 2026-09-09 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evidence", "0003_evidenceitem_is_synthetic_evidenceitem_limitations_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencehash",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evidencehash",
            name="file_metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="evidencehash",
            name="status",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="baseline_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="baseline_accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accepted_baselines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="baseline_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="baseline_origin",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="evidenceitem",
            name="baseline_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="evidenceitem",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("baseline_pending", "Local baseline pending acceptance"),
                    ("baseline_accepted", "Accepted local baseline comparison"),
                    ("verified", "Verified"),
                    ("mismatch", "Mismatch"),
                    ("unreadable", "Unreadable"),
                ],
                default="unverified",
                max_length=30,
            ),
        ),
    ]
