# Generated by Django 5.2.17 on 2026-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_legacy_checkpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="record_bindings",
            field=models.JSONField(default=dict),
        ),
    ]
