# Generated by Django 5.1.11 on 2026-08-19 13:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("evidence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="cases.case",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_jobs",
                        to="evidence.evidenceitem",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("processor_name", models.CharField(max_length=100)),
                ("processor_version", models.CharField(max_length=40)),
                ("status", models.CharField(default="running", max_length=30)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_runs",
                        to="cases.case",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="processing.processingjob",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(fields=["case", "status"], name="processing__case_id_5d68a4_idx"),
        ),
        migrations.AddIndex(
            model_name="processingjob",
            index=models.Index(
                fields=["evidence", "created_at"], name="processing__evidenc_f06360_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingrun",
            index=models.Index(fields=["case", "status"], name="processing__case_id_ca2938_idx"),
        ),
        migrations.AddIndex(
            model_name="processingrun",
            index=models.Index(fields=["job", "started_at"], name="processing__job_id_4d5241_idx"),
        ),
    ]
