# Generated by Django 5.2.17 on 2026-09-09 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_initial"),
        ("evidence", "0004_evidencehash_actor_evidencehash_file_metadata_and_more"),
        ("processing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="claim_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="claimed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="parameters",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="prior_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="processing.processingjob",
            ),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="publication_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="publication_status",
            field=models.CharField(default="pending", max_length=30),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="request_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="attempt_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="processingrun",
            name="reproducibility",
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name="processingjob",
            constraint=models.UniqueConstraint(
                fields=("case", "request_key"), name="job_case_request_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="processingrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "succeeded"), ("attempt_token__isnull", False)),
                fields=("job",),
                name="one_successful_run_per_job",
            ),
        ),
    ]
