# Generated by Django 5.2.17 on 2026-09-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_initial"),
        ("processing", "0002_processingjob_claim_token_processingjob_claimed_at_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="processingrun",
            name="one_successful_run_per_job",
        ),
        migrations.AddConstraint(
            model_name="processingrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt_token__isnull", False), ("status", "succeeded")),
                fields=("job",),
                name="one_successful_run_per_job",
            ),
        ),
    ]
